server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      jdbc-url: jdbc:h2:mem:USER
      password:


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  naver:
    X-Naver-Client-Id: 0QJhbYw2IhHIs78ihpxV
    X-Naver-Client-Secret: LSz5CRvuF4

  weather:
    encId : "u3c%2BFM4W0o9PJttotd3XxnLfGZlnRY09U9h2ZijN%2FQmAVXffmyX5d81ebxLxlSxDr6H6ajh5KQq%2BCKdzDtbK1g%3D%3D"
    decId : "u3c+FM4W0o9PJttotd3XxnLfGZlnRY09U9h2ZijN/QmAVXffmyX5d81ebxLxlSxDr6H6ajh5KQq+CKdzDtbK1g=="
    url : "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0"
