server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

#  datasource:
#    hikari:
#      driver-class-name: org.h2.Driver
#      username: sa
#      jdbc-url: jdbc:h2:mem:user
#      password:

 # difference in h2 DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: as2646
    url: jdbc:mysql://localhost:3306/spring

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  security:
    user:
      name: user
      password: 1234
      roles: USER